# Generated by Django 6.0.4 on 2026-07-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('rating', models.IntegerField(default=5)),
                ('status', models.CharField(default='Mavjud', max_length=50)),
                ('brand', models.CharField(default="Noma'lum", max_length=100)),
                ('color', models.CharField(default='Standart', max_length=50)),
                ('size', models.CharField(default='Standart', max_length=50)),
                ('material', models.CharField(default="Noma'lum", max_length=100)),
            ],
        ),
    ]
